new test functions; run function as arg; refactor
- Refactor arguments parsing
  - Substitute `getopt` command for `getopts` builtin.
- Allow executing test functions without sourcing. E.g.:
  - `aserta -v assert_success 'true'`  # prints `.`
  - `aserta -v assert_sucess  'false'` # prints `X`
  - `aserta -x assert_success 'false'` # prints error report
- New function:
  - `assert_NOTcontains`.
- New functions for string comparison:
  - `assert_str_equals`.
  - `assert_str_NOTequals`.
  - `assert_str_contains`.
  - `assert_str_NOTcontains`.
  - `assert_str_startswith`.
  - `assert_str_endswith`.
  - `assert_str_matches`.
- Refactor script.
  - Reorder functions.
  - Refactor `_assert_with_grep()`.
  - Remove multi-argument support for `assert_matches` and `assert_contains`.
  - Use Bash string comparison instead of grep in `assert_contains`.
- Update tests accordingly.
- Update usage help info.
- Update README.
  - Extend examples.
  - Add new functions.
  - Fix `--discover` long option.
  - Minor updates and fixes.
- Version 2.1.0

diff --git a/aserta b/aserta
--- a/aserta
+++ b/aserta
@@ -3,7 +3,7 @@
 # aserta
 # a handy unit testing framework
 #
-# Version    : 2.0.1
+# Version    : 2.1.0
 # Repository : http://github.com/andamira/aserta
 # Authors    :
 #   - Robert Lehmann © 2009-2015
@@ -27,55 +27,90 @@ main() {
 	: "${tests_ran_total:=0}"	  # remember total number of tests (inc. failures)
 	: "${tests_failed_total:=0}"  # remember the total number of test failures
 
-
 	trap _assert_cleanup EXIT
-
 
 	_indent=$'\n\t' # local format helper
 
-
-	parseArgs "$@"
-
 	# Commands substitutions
 	GREP=$(_cmd grep)
+
+	parseArguments "$@"
 
 } # main()
 
 
 #-------------------------------------------------------------------------------
-# parseArgs
+# parseArguments
 #
 #   Parses the arguments received by the script and sets the pertinent options.
 #
 # Arguments:
 #   $@ - all the arguments passed to the script
 #
-parseArgs() {
-	args="$(getopt -n "$0" -l \
-		verbose,help,stop,discover,invariant,continue vhxdic "$*")" || exit 255
+parseArguments() {
+	local OPTIND option value function
+	local optspec=":cdivxh-:"
 
-	for arg in $args; do
-		case "$arg" in
-			-h) usage false; exit 0 ;;
+	# Firstly parse the options
+	while getopts "$optspec" option; do
+		case "$option" in
+			-) # http://stackoverflow.com/a/7680682/940200 (long options)
+				case "$OPTARG" in
+					continue)  CONTINUE=1     ;;
+					discover)  DISCOVERONLY=1 ;;
+					invariant) INVARIANT=1    ;;
+					verbose)   DEBUG=1        ;;
+					stop)      STOP=1         ;;
+					help) usage true; exit 0  ;;
+					*)
+						if [[ "$OPTERR" == 1 && "${optspec:0:1}" != ":" ]]; then
+							echo "Unknown option --$OPTARG" >&2
+							exit 255
+						fi
+						;;
+				esac ;;
 
-			--help) usage true; exit 0 ;;
+			c) CONTINUE=1     ;;
+			d) DISCOVERONLY=1 ;;
+			i) INVARIANT=1    ;;
+			v) DEBUG=1        ;;
+			x) STOP=1         ;;
+			h) usage false; exit 0 ;;
 
-			-v|--verbose)
-				DEBUG=1 ;;
-
-			-x|--stop)
-				STOP=1 ;;
-
-			-i|--invariant)
-				INVARIANT=1 ;;
-
-			-d|--discover)
-				DISCOVERONLY=1 ;;
-
-			-c|--continue)
-				CONTINUE=1 ;;
+			*) echo "opterr=$OPTERR OPTSPEC=$optspec OPTARG=$OPTARG"
+				if [[ "$OPTERR" != 1 || "${optspec:0:1}" == ":" ]]; then
+					echo "Non-option argument: '-${OPTARG}'" >&2
+					exit 255
+				fi
+				;;
 		esac
 	done
+	shift $((OPTIND-1))
+
+	# Secondly parse an optional test function
+	function="$1"; shift
+	case "$function" in
+		assert_raises) assert_raises                   "$1" "$2" ;;
+		assert_success) assert_success                      "$1" ;;
+		assert_failure) assert_failure                      "$1" ;;
+
+		assert) assert                                 "$1" "$2" ;;
+		assert_startswith) assert_startswith           "$1" "$2" ;;
+		assert_endswith) assert_endswith               "$1" "$2" ;;
+		assert_contains) assert_contains               "$1" "$2" ;;
+		assert_NOTcontains) assert_NOTcontains         "$1" "$2" ;;
+		assert_matches) assert_matches                 "$1" "$2" ;;
+
+		assert_str_equals) assert_str_equals           "$1" "$2" ;;
+		assert_str_NOTequals) assert_str_NOTequals     "$1" "$2" ;;
+		assert_str_startswith) assert_str_startswith   "$1" "$2" ;;
+		assert_str_endswith) assert_str_endswith       "$1" "$2" ;;
+		assert_str_contains) assert_str_contains       "$1" "$2" ;;
+		assert_str_NOTcontains) assert_str_NOTcontains "$1" "$2" ;;
+		assert_str_matches) assert_str_matches         "$1" "$2" ;;
+		'') ;;
+		*) echo "unknown options"; exit 255 ;;
+	esac
 
 } # parseArgs()
 
@@ -94,7 +129,8 @@ usage() {
 	if [[ "$long" == true ]]; then
 
 		cat <<- "EOF"
-		Usage: $0 [options]
+		Usage: $0 [options] [assert_function] [arguments]
+
 		Language-agnostic unit tests for subprocesses.
 
 		Options:
@@ -107,12 +143,69 @@ usage() {
 		  --help           show this help message and exit
 		EOF
 	else
-		echo "$0 [-vxidc]" \
-			"[--verbose] [--stop] [--invariant] [--discover] [--continue]"
+		echo "$0 [-vxidc] [assert_function] [args]"
 		echo "$(sed 's/./ /g' <<< "$0") [-h] [--help]"
 	fi
 
 } # usage()
+
+
+#-------------------------------------------------------------------------------
+# _cmd <command>
+#
+#   Returns the resolved command, preferring gnu-versions on non-Linux systems,
+#   such as Mac OS, and falling back to the standard version when not found.
+#
+_cmd() {
+	declare default_cmd gnu_cmd gnu_cmd_found
+
+	default_cmd="$1"
+	gnu_cmd="g$default_cmd"
+	gnu_cmd_found=$(which "$gnu_cmd" 2> /dev/null)
+
+	if [ "$gnu_cmd_found" ]; then
+		echo "$gnu_cmd_found"
+	else
+		if [ "$(uname)" == 'Darwin' ]; then
+			echo "Warning: Cannot find gnu version of command '$cmd' ($gnu_cmd) on path." \
+				"Falling back to standard command" >&2
+		fi
+		echo "$default_cmd"
+	fi
+
+} # _cmd()
+
+
+#-------------------------------------------------------------------------------
+# _assert_cleanup
+#
+#   gets called on script exit
+#
+_assert_cleanup() {
+	local status=$?
+
+	# modify exit code if it's not already non-zero
+	[[ $status -eq 0 && -z $CONTINUE ]] && exit "$tests_suite_status"
+
+} # _assert_cleanup()
+
+
+#-------------------------------------------------------------------------------
+# _assert_fail <failure> <command> <stdin>
+#
+_assert_fail() {
+	[[ -n "$DEBUG" ]] && echo -n X
+	report="test #$tests_ran \"$2${3:+ <<< $3}\" failed:${_indent}$1"
+	if [[ -n "$STOP" ]]; then
+		[[ -n "$DEBUG" ]] && echo
+		echo "$report"
+		exit 1
+	fi
+	tests_errors[$tests_failed]="$report"
+	(( tests_failed++ )) || :
+	return 1
+
+} # _assert_fail()
 
 
 #-------------------------------------------------------------------------------
@@ -125,6 +218,74 @@ _assert_reset() {
 	tests_starttime="$(date +%s%N)" # nanoseconds_since_epoch
 
 } # _assert_reset()
+
+
+#-------------------------------------------------------------------------------
+# _assert_with_grep <grep modifiers> <string> <pattern>
+#
+_assert_with_grep() {
+	local modifier="$1"
+	local string="$2"
+	local pattern="$3"
+
+	assert_success "echo '$string' | $GREP $modifier '$pattern'" || return 1
+
+} # _assert_with_grep()
+
+
+
+# TEST FUNCTIONS: FLOW CONTROL
+# ============================
+
+
+#-------------------------------------------------------------------------------
+# skip_if <command ..>
+#
+skip_if() {
+	(eval "$@") > /dev/null 2>&1 && status=0 || status="$?"
+	[[ "$status" -eq 0 ]] || return
+	skip
+
+} # skip_if()
+
+
+#-------------------------------------------------------------------------------
+# skip (no arguments)
+#
+skip() {
+	shopt -q extdebug && tests_extdebug=0 || tests_extdebug=1
+	shopt -q -o errexit && tests_errexit=0 || tests_errexit=1
+
+	# enable extdebug so returning 1 in a DEBUG trap handler skips next command
+	shopt -s extdebug
+
+	# disable errexit (set -e) so we can safely return 1 without causing exit
+	set +o errexit
+	tests_trapped=0
+	trap _skip DEBUG
+
+} # skip()
+
+
+#-------------------------------------------------------------------------------
+# _skip
+#
+_skip() {
+	if [[ $tests_trapped -eq 0 ]]; then
+		# DEBUG trap for command we want to skip. Do not remove the handler
+		# yet because *after* the command we need to reset extdebug/errexit
+		# (in another DEBUG trap).
+		tests_trapped=1
+		[[ -z "$DEBUG" ]] || echo -n s
+		return 1
+	else
+		trap - DEBUG
+		[[ $tests_extdebug -eq 0 ]] || shopt -u extdebug
+		[[ $tests_errexit -eq 1 ]] || set -o errexit
+		return 0
+	fi
+
+} # _skip()
 
 
 #-------------------------------------------------------------------------------
@@ -165,24 +326,9 @@ assert_end() {
 } # assert_end()
 
 
-#-------------------------------------------------------------------------------
-# assert <command> <expected stdout> [stdin]
-#
-assert() {
-	(( tests_ran++ )) || :
-	[[ -z "$DISCOVERONLY" ]] || return
-	expected=$(echo -ne "${2:-}")
-	result=$(echo -e "$(eval 2>/dev/null "$1" <<< "${3:-}")")
-	if [[ "$result" == "$expected" ]]; then
-		[[ -z "$DEBUG" ]] || echo -n .
-		return
-	fi
-	result="$(sed -e :a -e '$!N;s/\n/\\n/;ta' <<< "$result")"
-	[[ -z "$result" ]] && result="nothing" || result="\"$result\""
-	[[ -z "$2" ]] && expected="nothing" || expected="\"$2\""
-	_assert_fail "expected $expected${_indent}got $result" "$1" "${3:-}"
 
-} # assert()
+# TEST FUNCTIONS: RETURN STATUS
+# =============================
 
 
 #-------------------------------------------------------------------------------
@@ -202,86 +348,6 @@ assert_raises() {
 		"$1" "$3"
 
 } # assert_raises()
-
-
-#-------------------------------------------------------------------------------
-# _assert_fail <failure> <command> <stdin>
-#
-_assert_fail() {
-	[[ -n "$DEBUG" ]] && echo -n X
-	report="test #$tests_ran \"$2${3:+ <<< $3}\" failed:${_indent}$1"
-	if [[ -n "$STOP" ]]; then
-		[[ -n "$DEBUG" ]] && echo
-		echo "$report"
-		exit 1
-	fi
-	tests_errors[$tests_failed]="$report"
-	(( tests_failed++ )) || :
-	return 1
-
-} # _assert_fail()
-
-
-#-------------------------------------------------------------------------------
-# skip_if <command ..>
-#
-skip_if() {
-	(eval "$@") > /dev/null 2>&1 && status=0 || status="$?"
-	[[ "$status" -eq 0 ]] || return
-	skip
-
-} # skip_if()
-
-
-#-------------------------------------------------------------------------------
-# skip (no arguments)
-#
-skip() {
-	shopt -q extdebug && tests_extdebug=0 || tests_extdebug=1
-	shopt -q -o errexit && tests_errexit=0 || tests_errexit=1
-
-	# enable extdebug so returning 1 in a DEBUG trap handler skips next command
-	shopt -s extdebug
-
-	# disable errexit (set -e) so we can safely return 1 without causing exit
-	set +o errexit
-	tests_trapped=0
-	trap _skip DEBUG
-
-} # skip
-
-
-#-------------------------------------------------------------------------------
-# _skip
-_skip() {
-	if [[ $tests_trapped -eq 0 ]]; then
-		# DEBUG trap for command we want to skip. Do not remove the handler
-		# yet because *after* the command we need to reset extdebug/errexit
-		# (in another DEBUG trap).
-		tests_trapped=1
-		[[ -z "$DEBUG" ]] || echo -n s
-		return 1
-	else
-		trap - DEBUG
-		[[ $tests_extdebug -eq 0 ]] || shopt -u extdebug
-		[[ $tests_errexit -eq 1 ]] || set -o errexit
-		return 0
-	fi
-
-} # _skip()
-
-
-#-------------------------------------------------------------------------------
-# _assert_cleanup
-#
-#   gets called on script exit
-#
-_assert_cleanup() {
-	local status=$?
-
-	# modify exit code if it's not already non-zero
-	[[ $status -eq 0 && -z $CONTINUE ]] && exit $tests_suite_status
-}
 
 
 #-------------------------------------------------------------------------------
@@ -310,24 +376,48 @@ assert_failure() {
 } # assert_failure()
 
 
+
+# TEST FUNCTIONS: EXPECTED OUTPUT
+# ===============================
+
+
 #-------------------------------------------------------------------------------
-# assert_contains <command> <expected output...>
+# assert <command> <expected stdout> [stdin]
+#
+assert() {
+	(( tests_ran++ )) || :
+	[[ -z "$DISCOVERONLY" ]] || return
+	expected=$(echo -ne "${2:-}")
+	result=$(echo -e "$(eval 2>/dev/null "$1" <<< "${3:-}")")
+	if [[ "$result" == "$expected" ]]; then
+		[[ -z "$DEBUG" ]] || echo -n .
+		return
+	fi
+	result="$(sed -e :a -e '$!N;s/\n/\\n/;ta' <<< "$result")"
+	[[ -z "$result" ]] && result="nothing" || result="\"$result\""
+	[[ -z "$2" ]] && expected="nothing" || expected="\"$2\""
+	_assert_fail "expected $expected${_indent}got $result" "$1" "${3:-}"
+
+} # assert()
+
+
+#-------------------------------------------------------------------------------
+# assert_contains <command> <expected part of STDOUT>
 #
 assert_contains() {
-	_assert_with_grep '-F' "$@"
+	assert_success "[[ '$($1)' == *'$2'* ]]"
 }
 
-
 #-------------------------------------------------------------------------------
-# assert_matches <command> <expected output...>
+# assert_NOTcontains <command> <not expected part of STDOUT>
 #
-assert_matches() {
-	_assert_with_grep '-E' "$@"
+assert_NOTcontains() {
+	assert_success "[[ '$($1)' != *'$2'* ]]"
 }
 
 
 #-------------------------------------------------------------------------------
-# assert_startswith <command> <expected start to stdout>
+# assert_startswith <command> <expected start of STDOUT>
 #
 assert_startswith() {
 	assert_success "[[ '$($1)' == '$2'* ]]"
@@ -335,51 +425,79 @@ assert_startswith() {
 
 
 #-------------------------------------------------------------------------------
-# assert_endswith <command> <expected end to stdout>
+# assert_endswith <command> <expected end of STDOUT>
 #
 assert_endswith() {
 	assert_success "[[ '$($1)' == *'$2' ]]"
 }
 
-#-------------------------------------------------------------------------------
-# _assert_with_grep <grep modifiers> <command> <expected output...>
-#
-_assert_with_grep() {
-	local grep_modifier="$1"
-	local output; output="$($2)"
-	shift 2
 
-	while [ $# != 0 ]; do
-		assert_raises "echo '$output' | $GREP $grep_modifier '$1'" 0 || return 1
-		shift
-	done
+#-------------------------------------------------------------------------------
+# assert_matches <command> <expected matching pattern>
+#
+assert_matches() {
+	_assert_with_grep '-E' "$($1)" "$2"
+}
+
+
+
+# TEST FUNCTIONS: STRING COMPARISON
+# ============================
+
+
+#-------------------------------------------------------------------------------
+# assert_str_equals <string> <expected string>
+#
+assert_str_equals() {
+	assert_success "[[ '$1' == '$2' ]]"
+}
+
+
+#-------------------------------------------------------------------------------
+# assert_str_NOTequals <string> <not expected string>
+#
+assert_str_NOTequals() {
+	assert_success "[[ '$1' != '$2' ]]"
+}
+
+
+#-------------------------------------------------------------------------------
+# assert_str_startswith <string> <expected start to the string>
+#
+assert_str_startswith() {
+	assert_success "[[ '$1' == '$2'* ]]"
+}
+
+
+#-------------------------------------------------------------------------------
+# assert_str_endswith <command> <expected end to the string>
+#
+assert_str_endswith() {
+	assert_success "[[ '$1' == *'$2' ]]"
+}
+
+
+#-------------------------------------------------------------------------------
+# assert_str_contains <command> <expected part of the string>
+#
+assert_str_contains() {
+	assert_success "[[ '$1' == *'$2'* ]]"
 }
 
 #-------------------------------------------------------------------------------
-#   _cmd
+# assert_str_NOTcontains <string> <not expected part of the string>
 #
-#   Returns the resolved command, preferring gnu-versions (prefixed with 'g')
-#   on non-Linux systems such as Mac OS, and falling back to the standard version if not.
-#
-# Arguments:
-#  $1 - default command
-#
-_cmd() {
-	declare default_cmd gnu_cmd gnu_cmd_found
-
-	default_cmd="$1"
-	gnu_cmd="g$default_cmd"
-	gnu_cmd_found=$(which "$gnu_cmd" 2> /dev/null)
-
-	if [ "$gnu_cmd_found" ]; then
-		echo "$gnu_cmd_found"
-	else
-		if [ "$(uname)" == 'Darwin' ]; then
-			echo "Warning: Cannot find gnu version of command '$cmd' ($gnu_cmd) on path." \
-				"Falling back to standard command" >&2
-		fi
-		echo "$default_cmd"
-	fi
+assert_str_NOTcontains() {
+	assert_success "[[ '$1' != *'$2'* ]]"
 }
+
+
+#-------------------------------------------------------------------------------
+# assert_str_matches <string> <expected matching pattern>
+#
+assert_str_matches() {
+	_assert_with_grep '-E' "$1" "$2"
+}
+
 
 main "$@"
