refactor; fixes; update tests & README
- Change all `echo` with `printf`.
- Fix arguments parsing, improve messages.
- Version 2.1.1

diff --git a/aserta b/aserta
--- a/aserta
+++ b/aserta
@@ -3,7 +3,7 @@
 # aserta
 # a handy unit testing framework
 #
-# Version    : 2.1.0
+# Version    : 2.1.1
 # Repository : http://github.com/andamira/aserta
 # Authors    :
 #   - Robert Lehmann © 2009-2015
@@ -48,13 +48,18 @@ main() {
 #   $@ - all the arguments passed to the script
 #
 parseArguments() {
-	local OPTIND option value function
+	local OPTIND option function
 	local optspec=":cdivxh-:"
 
-	# Firstly parse the options
+	# First parse the options
+
 	while getopts "$optspec" option; do
 		case "$option" in
-			-) # http://stackoverflow.com/a/7680682/940200 (long options)
+
+			# long options
+			# http://stackoverflow.com/a/7680682/940200
+
+			-)
 				case "$OPTARG" in
 					continue)  CONTINUE=1     ;;
 					discover)  DISCOVERONLY=1 ;;
@@ -62,13 +67,15 @@ parseArguments() {
 					verbose)   DEBUG=1        ;;
 					stop)      STOP=1         ;;
 					help) usage true; exit 0  ;;
-					*)
-						if [[ "$OPTERR" == 1 && "${optspec:0:1}" != ":" ]]; then
-							echo "Unknown option --$OPTARG" >&2
+
+					*)  # error
+						if [[ "$OPTERR" == 1 ]]; then
+							printf 'Unknown option --%s\n' "$OPTARG" >&2
 							exit 255
-						fi
-						;;
+						fi ;;
 				esac ;;
+
+			# short options
 
 			c) CONTINUE=1     ;;
 			d) DISCOVERONLY=1 ;;
@@ -77,19 +84,22 @@ parseArguments() {
 			x) STOP=1         ;;
 			h) usage false; exit 0 ;;
 
-			*) echo "opterr=$OPTERR OPTSPEC=$optspec OPTARG=$OPTARG"
+			*)  # error
 				if [[ "$OPTERR" != 1 || "${optspec:0:1}" == ":" ]]; then
-					echo "Non-option argument: '-${OPTARG}'" >&2
+					printf "Non-option argument: '-%s'\n" "${OPTARG}" >&2
 					exit 255
-				fi
-				;;
+				fi ;;
 		esac
 	done
 	shift $((OPTIND-1))
 
-	# Secondly parse an optional test function
+	# Secondly, parse an optional test function
+
 	function="$1"; shift
 	case "$function" in
+
+		# supported functions
+
 		assert_raises) assert_raises                   "$1" "$2" ;;
 		assert_success) assert_success                      "$1" ;;
 		assert_failure) assert_failure                      "$1" ;;
@@ -108,8 +118,19 @@ parseArguments() {
 		assert_str_contains) assert_str_contains       "$1" "$2" ;;
 		assert_str_NOTcontains) assert_str_NOTcontains "$1" "$2" ;;
 		assert_str_matches) assert_str_matches         "$1" "$2" ;;
-		'') ;;
-		*) echo "unknown options"; exit 255 ;;
+
+		# unsupported functions
+
+		assert_end|skip|skip_if)
+			printf "Test function '%s' not supported as a script argument\n" \
+				"$function"
+			exit 255 ;;
+
+		'') ;; # no function
+
+		*)  # error
+			printf "Unknown test function: '%s'\n" "$function"
+			exit 255 ;;
 	esac
 
 } # parseArgs()
@@ -143,8 +164,8 @@ usage() {
 		  --help           show this help message and exit
 		EOF
 	else
-		echo "$0 [-vxidc] [assert_function] [args]"
-		echo "$(sed 's/./ /g' <<< "$0") [-h] [--help]"
+		printf '%s [-vxidc] [assert_function] [args]\n' "$0"
+		printf "%s [-h] [--help]\n" "$(sed 's/./ /g' <<< "$0")"
 	fi
 
 } # usage()
@@ -164,13 +185,13 @@ _cmd() {
 	gnu_cmd_found=$(which "$gnu_cmd" 2> /dev/null)
 
 	if [ "$gnu_cmd_found" ]; then
-		echo "$gnu_cmd_found"
+		printf '%s' "$gnu_cmd_found"
 	else
 		if [ "$(uname)" == 'Darwin' ]; then
-			echo "Warning: Cannot find gnu version of command '$cmd' ($gnu_cmd) on path." \
-				"Falling back to standard command" >&2
+			printf "Warning: Cannot find gnu version of command '%s' (%s) on path." \
+				"Falling back to standard command" "$default_cmd" "$gnu_cmd" >&2
 		fi
-		echo "$default_cmd"
+		printf '%s' "$default_cmd"
 	fi
 
 } # _cmd()
@@ -194,11 +215,11 @@ _assert_cleanup() {
 # _assert_fail <failure> <command> <stdin>
 #
 _assert_fail() {
-	[[ -n "$DEBUG" ]] && echo -n X
+	[[ -n "$DEBUG" ]] && printf 'X'
 	report="test #$tests_ran \"$2${3:+ <<< $3}\" failed:${_indent}$1"
 	if [[ -n "$STOP" ]]; then
-		[[ -n "$DEBUG" ]] && echo
-		echo "$report"
+		[[ -n "$DEBUG" ]] && printf '\n'
+		printf '%s\n' "$report"
 		exit 1
 	fi
 	tests_errors[$tests_failed]="$report"
@@ -223,12 +244,14 @@ _assert_reset() {
 #-------------------------------------------------------------------------------
 # _assert_with_grep <grep modifiers> <string> <pattern>
 #
+# NOTE: doesn't support newlines in the pattern
+#
 _assert_with_grep() {
 	local modifier="$1"
 	local string="$2"
 	local pattern="$3"
 
-	assert_success "echo '$string' | $GREP $modifier '$pattern'" || return 1
+	assert_success "printf '$string' | $GREP $modifier '$pattern'" || return 1
 
 } # _assert_with_grep()
 
@@ -276,7 +299,7 @@ _skip() {
 		# yet because *after* the command we need to reset extdebug/errexit
 		# (in another DEBUG trap).
 		tests_trapped=1
-		[[ -z "$DEBUG" ]] || echo -n s
+		[[ -z "$DEBUG" ]] || printf 's'
 		return 1
 	else
 		trap - DEBUG
@@ -300,9 +323,9 @@ assert_end() {
 			- ${tests_starttime/%N/000000000} ))")"  # in ns
 	tests="$tests_ran ${*:+$* }tests"
 
-	[[ -n "$DISCOVERONLY" ]] && echo "collected $tests." \
+	[[ -n "$DISCOVERONLY" ]] && printf 'collected %s.\n' "$tests" \
 		&& _assert_reset && return
-	[[ -n "$DEBUG" ]] && echo
+	[[ -n "$DEBUG" ]] && printf '\n'
 
 	# to get report_time split tests_time on 2 substrings:
 	#   ${tests_time:0:${#tests_time}-9} - seconds
@@ -312,10 +335,10 @@ assert_end() {
 	else report_time=; fi
 
 	if [[ "$tests_failed" -eq 0 ]]; then
-		echo "all $tests passed$report_time."
+		printf 'all %s passed%s.\n' "$tests" "$report_time"
 	else
-		for error in "${tests_errors[@]}"; do echo "$error"; done
-		echo "$tests_failed of $tests failed$report_time."
+		for error in "${tests_errors[@]}"; do printf '%s\n' "$error"; done
+		printf '%d of %s failed%s.\n' "$tests_failed" "$tests" "$report_time"
 	fi
 
 	tests_ran_total=$((tests_ran_total + tests_ran))
@@ -341,7 +364,7 @@ assert_raises() {
 	(eval "$1" <<< "${3:-}") > /dev/null 2>&1 || status="$?"
 	expected=${2:-0}
 	if [[ "$status" -eq "$expected" ]]; then
-		[[ -z "$DEBUG" ]] || echo -n .
+		[[ -z "$DEBUG" ]] || printf '.'
 		return
 	fi
 	_assert_fail "program terminated with code $status instead of $expected" \
@@ -367,7 +390,7 @@ assert_failure() {
 	status=0
 	(eval "$1" <<< "${2:-}") > /dev/null 2>&1 || status="$?"
 	if [[ "$status" != "0" ]]; then
-		[[ -z "$DEBUG" ]] || echo -n .
+		[[ -z "$DEBUG" ]] || printf '.'
 		return
 	fi
 	_assert_fail "program terminated with a zero return code; expecting non-zero return code" \
@@ -387,10 +410,12 @@ assert_failure() {
 assert() {
 	(( tests_ran++ )) || :
 	[[ -z "$DISCOVERONLY" ]] || return
-	expected=$(echo -ne "${2:-}")
-	result=$(echo -e "$(eval 2>/dev/null "$1" <<< "${3:-}")")
+	# shellcheck disable=SC2059
+	expected=$(printf "${2:-}")
+	# shellcheck disable=SC2059
+	result=$(printf "$(eval 2>/dev/null "$1" <<< "${3:-}")")
 	if [[ "$result" == "$expected" ]]; then
-		[[ -z "$DEBUG" ]] || echo -n .
+		[[ -z "$DEBUG" ]] || printf '.'
 		return
 	fi
 	result="$(sed -e :a -e '$!N;s/\n/\\n/;ta' <<< "$result")"
