refactor into functions; minor updates
- Refactor script
  - New main function;
  - Move all code inside functions.
  - New usage function.
  - Add function header comments.
- Change err exit code -1 to 255.
- Update README; update badges.
- Version 2.0.1

diff --git a/aserta b/aserta
--- a/aserta
+++ b/aserta
@@ -3,75 +3,133 @@
 # aserta
 # a handy unit testing framework
 #
-# Version    : 2.0.0
+# Version    : 2.0.1
 # Repository : http://github.com/andamira/aserta
 # Authors    :
 #   - Robert Lehmann © 2009-2015
 #   - José Luis Cruz © 2016
 # License    : LGPLv3
+
+
+#-------------------------------------------------------------------------------
+# main
 #
+main() {
 
-export DISCOVERONLY="${DISCOVERONLY:-}"
-export DEBUG="${DEBUG:-}"
-export STOP="${STOP:-}"
-export INVARIANT="${INVARIANT:-}"
-export CONTINUE="${CONTINUE:-}"
+	export DISCOVERONLY="${DISCOVERONLY:-}"
+	export DEBUG="${DEBUG:-}"
+	export STOP="${STOP:-}"
+	export INVARIANT="${INVARIANT:-}"
+	export CONTINUE="${CONTINUE:-}"
 
-args="$(getopt -n "$0" -l \
-	verbose,help,stop,discover,invariant,continue vhxdic "$*")" || exit -1
+	_assert_reset
+	: "${tests_suite_status:=0}"  # remember if any of the tests failed so far
+	: "${tests_ran_total:=0}"	  # remember total number of tests (inc. failures)
+	: "${tests_failed_total:=0}"  # remember the total number of test failures
 
-for arg in $args; do
-	case "$arg" in
-		-h)
-			echo "$0 [-vxidc]" \
-				"[--verbose] [--stop] [--invariant] [--discover] [--continue]"
-			echo "$(sed 's/./ /g' <<< "$0") [-h] [--help]"
-			exit 0 ;;
 
-		--help)
-			cat <<- EOF
-			Usage: $0 [options]
-			Language-agnostic unit tests for subprocesses.
+	trap _assert_cleanup EXIT
 
-			Options:
-			  -v, --verbose    generate output for every individual test case
-			  -x, --stop       stop running tests after the first failure
-			  -i, --invariant  do not measure timings to remain invariant between runs
-			  -d, --discover   collect test suites only, do not run any tests
-			  -c, --continue   do not modify exit code to test suite status
-			  -h               show brief usage information and exit
-			  --help           show this help message and exit
-			EOF
-			exit 0 ;;
 
-		-v|--verbose)
-			DEBUG=1 ;;
+	_indent=$'\n\t' # local format helper
 
-		-x|--stop)
-			STOP=1 ;;
 
-		-i|--invariant)
-			INVARIANT=1 ;;
+	parseArgs "$@"
 
-		-d|--discover)
-			DISCOVERONLY=1 ;;
+	# Commands substitutions
+	GREP=$(_cmd grep)
 
-		-c|--continue)
-			CONTINUE=1 ;;
-	esac
-done
+} # main()
 
-_indent=$'\n\t' # local format helper
 
+#-------------------------------------------------------------------------------
+# parseArgs
+#
+#   Parses the arguments received by the script and sets the pertinent options.
+#
+# Arguments:
+#   $@ - all the arguments passed to the script
+#
+parseArgs() {
+	args="$(getopt -n "$0" -l \
+		verbose,help,stop,discover,invariant,continue vhxdic "$*")" || exit 255
+
+	for arg in $args; do
+		case "$arg" in
+			-h) usage false; exit 0 ;;
+
+			--help) usage true; exit 0 ;;
+
+			-v|--verbose)
+				DEBUG=1 ;;
+
+			-x|--stop)
+				STOP=1 ;;
+
+			-i|--invariant)
+				INVARIANT=1 ;;
+
+			-d|--discover)
+				DISCOVERONLY=1 ;;
+
+			-c|--continue)
+				CONTINUE=1 ;;
+		esac
+	done
+
+} # parseArgs()
+
+
+#-------------------------------------------------------------------------------
+# usage
+#
+#   Print usage information
+#
+# Arguments:
+#  $1 - if true, print long usage
+#
+usage() {
+	local long="$1"
+
+	if [[ "$long" == true ]]; then
+
+		cat <<- "EOF"
+		Usage: $0 [options]
+		Language-agnostic unit tests for subprocesses.
+
+		Options:
+		  -v, --verbose    generate output for every individual test case
+		  -x, --stop       stop running tests after the first failure
+		  -i, --invariant  do not measure timings to remain invariant between runs
+		  -d, --discover   collect test suites only, do not run any tests
+		  -c, --continue   do not modify exit code to test suite status
+		  -h               show brief usage information and exit
+		  --help           show this help message and exit
+		EOF
+	else
+		echo "$0 [-vxidc]" \
+			"[--verbose] [--stop] [--invariant] [--discover] [--continue]"
+		echo "$(sed 's/./ /g' <<< "$0") [-h] [--help]"
+	fi
+
+} # usage()
+
+
+#-------------------------------------------------------------------------------
+# _assert_reset
+#
 _assert_reset() {
 	tests_ran=0
 	tests_failed=0
 	tests_errors=()
 	tests_starttime="$(date +%s%N)" # nanoseconds_since_epoch
-}
+
+} # _assert_reset()
 
 
+#-------------------------------------------------------------------------------
 # assert_end [suite ..]
+#
 assert_end() {
 	tests_endtime="$(date +%s%N)"
 
@@ -103,10 +161,13 @@ assert_end() {
 	tests_failed_total=$((tests_failed_total + tests_failed))
 	[[ $tests_failed -gt 0 ]] && tests_suite_status=1
 	_assert_reset
-}
+
+} # assert_end()
 
 
+#-------------------------------------------------------------------------------
 # assert <command> <expected stdout> [stdin]
+#
 assert() {
 	(( tests_ran++ )) || :
 	[[ -z "$DISCOVERONLY" ]] || return
@@ -120,10 +181,13 @@ assert() {
 	[[ -z "$result" ]] && result="nothing" || result="\"$result\""
 	[[ -z "$2" ]] && expected="nothing" || expected="\"$2\""
 	_assert_fail "expected $expected${_indent}got $result" "$1" "${3:-}"
-}
+
+} # assert()
 
 
+#-------------------------------------------------------------------------------
 # assert_raises <command> <expected code> [stdin]
+#
 assert_raises() {
 	(( tests_ran++ )) || :
 	[[ -z "$DISCOVERONLY" ]] || return
@@ -136,10 +200,13 @@ assert_raises() {
 	fi
 	_assert_fail "program terminated with code $status instead of $expected" \
 		"$1" "$3"
-}
+
+} # assert_raises()
 
 
+#-------------------------------------------------------------------------------
 # _assert_fail <failure> <command> <stdin>
+#
 _assert_fail() {
 	[[ -n "$DEBUG" ]] && echo -n X
 	report="test #$tests_ran \"$2${3:+ <<< $3}\" failed:${_indent}$1"
@@ -151,18 +218,24 @@ _assert_fail() {
 	tests_errors[$tests_failed]="$report"
 	(( tests_failed++ )) || :
 	return 1
-}
+
+} # _assert_fail()
 
 
+#-------------------------------------------------------------------------------
 # skip_if <command ..>
+#
 skip_if() {
 	(eval "$@") > /dev/null 2>&1 && status=0 || status="$?"
 	[[ "$status" -eq 0 ]] || return
 	skip
-}
+
+} # skip_if()
 
 
+#-------------------------------------------------------------------------------
 # skip (no arguments)
+#
 skip() {
 	shopt -q extdebug && tests_extdebug=0 || tests_extdebug=1
 	shopt -q -o errexit && tests_errexit=0 || tests_errexit=1
@@ -174,13 +247,17 @@ skip() {
 	set +o errexit
 	tests_trapped=0
 	trap _skip DEBUG
-}
 
+} # skip
+
+
+#-------------------------------------------------------------------------------
+# _skip
 _skip() {
 	if [[ $tests_trapped -eq 0 ]]; then
-		# DEBUG trap for command we want to skip.  Do not remove the handler
-		# yet because *after* the command we need to reset extdebug/errexit (in
-		# another DEBUG trap.)
+		# DEBUG trap for command we want to skip. Do not remove the handler
+		# yet because *after* the command we need to reset extdebug/errexit
+		# (in another DEBUG trap).
 		tests_trapped=1
 		[[ -z "$DEBUG" ]] || echo -n s
 		return 1
@@ -190,29 +267,34 @@ _skip() {
 		[[ $tests_errexit -eq 1 ]] || set -o errexit
 		return 0
 	fi
-}
+
+} # _skip()
 
 
-_assert_reset
-: ${tests_suite_status:=0}  # remember if any of the tests failed so far
-: ${tests_ran_total:=0}	    # remember total number of tests (inc. failures)
-: ${tests_failed_total:=0}  # remember the total number of test failures
-
+#-------------------------------------------------------------------------------
+# _assert_cleanup
+#
+#   gets called on script exit
+#
 _assert_cleanup() {
 	local status=$?
+
 	# modify exit code if it's not already non-zero
 	[[ $status -eq 0 && -z $CONTINUE ]] && exit $tests_suite_status
 }
 
-trap _assert_cleanup EXIT
 
-
+#-------------------------------------------------------------------------------
 # assert_success <command> [stdin]
+#
 assert_success() {
 	assert_raises "$1" 0 "${2:-}"
 }
 
+
+#-------------------------------------------------------------------------------
 # assert_failure <command> [stdin]
+#
 assert_failure() {
 	(( tests_ran++ )) || :
 	[[ -z "$DISCOVERONLY" ]] || return
@@ -224,29 +306,44 @@ assert_failure() {
 	fi
 	_assert_fail "program terminated with a zero return code; expecting non-zero return code" \
 		"$1" "$2"
-}
 
+} # assert_failure()
+
+
+#-------------------------------------------------------------------------------
 # assert_contains <command> <expected output...>
+#
 assert_contains() {
 	_assert_with_grep '-F' "$@"
 }
 
+
+#-------------------------------------------------------------------------------
 # assert_matches <command> <expected output...>
+#
 assert_matches() {
 	_assert_with_grep '-E' "$@"
 }
 
+
+#-------------------------------------------------------------------------------
 # assert_startswith <command> <expected start to stdout>
+#
 assert_startswith() {
 	assert_success "[[ '$($1)' == '$2'* ]]"
 }
 
+
+#-------------------------------------------------------------------------------
 # assert_endswith <command> <expected end to stdout>
+#
 assert_endswith() {
 	assert_success "[[ '$($1)' == *'$2' ]]"
 }
 
+#-------------------------------------------------------------------------------
 # _assert_with_grep <grep modifiers> <command> <expected output...>
+#
 _assert_with_grep() {
 	local grep_modifier="$1"
 	local output; output="$($2)"
@@ -258,13 +355,20 @@ _assert_with_grep() {
 	done
 }
 
-# Returns the resolved command, preferring any gnu-versions of the cmd (prefixed with 'g') on
-# non-Linux systems such as Mac OS, and falling back to the standard version if not.
+#-------------------------------------------------------------------------------
+#   _cmd
+#
+#   Returns the resolved command, preferring gnu-versions (prefixed with 'g')
+#   on non-Linux systems such as Mac OS, and falling back to the standard version if not.
+#
+# Arguments:
+#  $1 - default command
+#
 _cmd() {
-	declare cmd gnu_cmd gnu_cmd_found
+	declare default_cmd gnu_cmd gnu_cmd_found
 
-	cmd="$1"
-	gnu_cmd="g$cmd"
+	default_cmd="$1"
+	gnu_cmd="g$default_cmd"
 	gnu_cmd_found=$(which "$gnu_cmd" 2> /dev/null)
 
 	if [ "$gnu_cmd_found" ]; then
@@ -274,8 +378,8 @@ _cmd() {
 			echo "Warning: Cannot find gnu version of command '$cmd' ($gnu_cmd) on path." \
 				"Falling back to standard command" >&2
 		fi
-		echo "$cmd"
+		echo "$default_cmd"
 	fi
 }
 
-GREP=$(_cmd grep)
+main "$@"
